title: A Developer' Blog
description: by Adarsh Pastakia

url: http://adarshpastakia.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects
 - title: About
   url: /about

social:
   github: adarshpastakia
   email: adarshpastakia@outlook.com

# google_analytics: "UA-58263416-1"
